import crafttweaker.item.IIngredient;

import scripts.crafttweaker.stages.stageZero;
import scripts.crafttweaker.stages.stageOne;
import scripts.crafttweaker.stages.stageTwo;
import scripts.crafttweaker.stages.stageThree;

static stagedItems as IIngredient[][string] = {
	stageZero.stage: [
		<rustic:aloe_vera>,
		<rustic:apple_seeds>,
		<rustic:bee>,
		<rustic:beeswax>,
		<rustic:blood_orchid>,
		<rustic:chamomile>,
		<rustic:chili_pepper_seeds>,
		<rustic:chili_pepper>,
		<rustic:cloudsbluff>,
		<rustic:cohosh>,
		<rustic:core_root>,
		<rustic:deathstalk_mushroom>,
		<rustic:ginseng>,
		<rustic:grape_stem>,
		<rustic:grapes>,
		<rustic:honeycomb>,
		<rustic:horsetail>,
		<rustic:ironberries>,
		<rustic:ironwood_slab_item>,
		<rustic:leaves_apple>,
		<rustic:leaves:1>,
		<rustic:leaves>,
		<rustic:marsh_mallow>,
		<rustic:mooncap_mushroom>,
		<rustic:olive_slab_item>,
		<rustic:olives>,
		<rustic:painted_wood_black>,
		<rustic:painted_wood_blue>,
		<rustic:painted_wood_brown>,
		<rustic:painted_wood_cyan>,
		<rustic:painted_wood_gray>,
		<rustic:painted_wood_green>,
		<rustic:painted_wood_light_blue>,
		<rustic:painted_wood_lime>,
		<rustic:painted_wood_magenta>,
		<rustic:painted_wood_orange>,
		<rustic:painted_wood_pink>,
		<rustic:painted_wood_purple>,
		<rustic:painted_wood_red>,
		<rustic:painted_wood_silver>,
		<rustic:painted_wood_white>,
		<rustic:painted_wood_yellow>,
		<rustic:planks:1>,
		<rustic:planks>,
		<rustic:tallow>,
		<rustic:tomato_seeds>,
		<rustic:tomato>,
		<rustic:wind_thistle>
	],

	stageOne.stage: [
		// Fences and Doors
		<rustic:clay_wall_cross>,
		<rustic:clay_wall_diag>,
		<rustic:clay_wall>,
		<rustic:fence_gate_ironwood>,
		<rustic:fence_gate_olive>,
		<rustic:fence_ironwood>,
		<rustic:fence_olive>,
		<rustic:ironwood_door>,
		<rustic:olive_door>,

		// Misc
		<rustic:andesite_pillar>,
		<rustic:barrel>,
		<rustic:book>,
		<rustic:cabinet>,
		<rustic:chair_acacia>,
		<rustic:chair_big_oak>,
		<rustic:chair_birch>,
		<rustic:chair_ironwood>,
		<rustic:chair_jungle>,
		<rustic:chair_oak>,
		<rustic:chair_olive>,
		<rustic:chair_spruce>,
		<rustic:crop_stake>,
		<rustic:crushing_tub>,
		<rustic:diorite_pillar>,
		<rustic:evaporating_basin>,
		<rustic:granite_pillar>,
		<rustic:rope>,
		<rustic:slate_pillar>,
		<rustic:stairs_ironwood>,
		<rustic:stairs_olive>,
		<rustic:stone_pillar>,
		<rustic:table_acacia>,
		<rustic:table_big_oak>,
		<rustic:table_birch>,
		<rustic:table_ironwood>,
		<rustic:table_jungle>,
		<rustic:table_oak>,
		<rustic:table_olive>,
		<rustic:table_spruce>,
		<rustic:vase>
	],

	stageTwo.stage: [
		<rustic:apiary>,
		<rustic:beehive>,
		<rustic:brewing_barrel>,
		<rustic:candle>,
		<rustic:chain>,
		<rustic:chandelier>,
		<rustic:condenser_advanced>,
		<rustic:condenser>,
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:fire_resistance", Duration: 3600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:fire_resistance", Duration: 9600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:haste", Duration: 1800, Amplifier: 1}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:haste", Duration: 3600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:haste", Duration: 9600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:health_boost", Duration: 1800, Amplifier: 1}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:health_boost", Duration: 3600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:health_boost", Duration: 9600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:instant_health", Duration: 1, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:instant_health", Duration: 1, Amplifier: 1}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:night_vision", Duration: 3600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:night_vision", Duration: 9600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:regeneration", Duration: 450, Amplifier: 1}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:regeneration", Duration: 900, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:regeneration", Duration: 1800, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:speed", Duration: 1800, Amplifier: 1}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:speed", Duration: 3600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:speed", Duration: 9600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:strength", Duration: 1800, Amplifier: 1}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:strength", Duration: 3600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:strength", Duration: 9600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:wither", Duration: 450, Amplifier: 1}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:wither", Duration: 900, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:wither", Duration: 1800, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "rustic:blazing_trail", Duration: 3600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "rustic:blazing_trail", Duration: 9600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "rustic:feather", Duration: 3600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "rustic:feather", Duration: 9600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "rustic:ironskin", Duration: 1800, Amplifier: 1}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "rustic:ironskin", Duration: 3600, Amplifier: 0}]}),
		<rustic:elixir>.withTag({ElixirEffects: [{Effect: "rustic:ironskin", Duration: 9600, Amplifier: 0}]}),
		<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "ale", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
		<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "alewort", Amount: 1000}}),
		<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "applejuice", Amount: 1000}}),
		<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "cider", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
		<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "grapejuice", Amount: 1000}}),
		<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "honey", Amount: 1000}}),
		<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "ironberryjuice", Amount: 1000}}),
		<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "ironwine", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
		<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "mead", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
		<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "oliveoil", Amount: 1000}}),
		<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "wildberryjuice", Amount: 1000}}),
		<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "wildberrywine", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
		<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "wine", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
		<rustic:gargoyle>,
		<rustic:iron_lantern>,
		<rustic:iron_lattice>,
		<rustic:liquid_barrel>,
		<rustic:retort_advanced>,
		<rustic:retort>,
		<rustic:slate_brick_slab_item>,
		<rustic:slate_brick>,
		<rustic:slate_chiseled>,
		<rustic:slate_roof_slab_item>,
		<rustic:slate_roof>,
		<rustic:slate_tile>,
		<rustic:stairs_slate_brick>,
		<rustic:stairs_slate_roof>
	],

	stageThree.stage: [
		<rustic:elixir>,
		<rustic:fluid_bottle>
	]
};

function init() {
	for stageName, items in scripts.crafttweaker.staging.itemsAndRecipes.rustic.stagedItems {
		Stager.getStage(stageName).addIngredients(items);
	}
}
