import crafttweaker.item.IIngredient;

import mods.zenstages.ZenStager;

import scripts.crafttweaker.stages.stageZero;
import scripts.crafttweaker.stages.stageOne;
import scripts.crafttweaker.stages.stageTwo;
import scripts.crafttweaker.stages.stageThree;
import scripts.crafttweaker.stages.stageFive;
import scripts.crafttweaker.stages.stageDisabled;

static stagedItems as IIngredient[][string] = {
	stageZero.stage: [
		<betterwithaddons:bag:17>,
		<betterwithaddons:bundle:3>,
		<betterwithaddons:bundle:4>,
		<betterwithaddons:bundle:5>,
		<betterwithaddons:bundle:6>,
		<betterwithaddons:bundle:7>,
		<betterwithaddons:bundle:8>,
		<betterwithaddons:bundle>,
		<betterwithaddons:congealed:1>,
		<betterwithaddons:congealed:2>,
		<betterwithaddons:congealed:3>,
		<betterwithaddons:congealed:4>,
		<betterwithaddons:congealed>,
		<betterwithaddons:food_amanita_baked>,
		<betterwithaddons:food_beetroot_baked>,
		<betterwithaddons:food_bowl_rice>,
		<betterwithaddons:food_carrot_baked>,
		<betterwithaddons:food_cooked_rice>,
		<betterwithaddons:food_fugu_sac>,
		<betterwithaddons:food_ground_meat>,
		<betterwithaddons:food_mulberry>,
		<betterwithaddons:food_mushroom_baked>,
		<betterwithaddons:food_pie_amanita>,
		<betterwithaddons:food_pie_meat>,
		<betterwithaddons:food_pie_melon>,
		<betterwithaddons:food_pie_mushroom>,
		<betterwithaddons:food_pufferfish_cooked>,
		<betterwithaddons:food_pufferfish_prepared>,
		<betterwithaddons:food_sashimi>,
		<betterwithaddons:japanmat:1>,
		<betterwithaddons:japanmat:2>,
		<betterwithaddons:japanmat:3>,
		<betterwithaddons:japanmat:4>,
		<betterwithaddons:japanmat:5>,
		<betterwithaddons:japanmat>,
		<betterwithaddons:leaves_mulberry>,
		<betterwithaddons:leaves_sakura>,
		<betterwithaddons:log_mulberry>,
		<betterwithaddons:log_sakura>,
		<betterwithaddons:planks_mulberry>,
		<betterwithaddons:planks_sakura>,
		<betterwithaddons:salt>,
		<betterwithaddons:sapling_mulberry>,
		<betterwithaddons:sapling_sakura>,
		<betterwithaddons:tatami>,
		<betterwithaddons:tweakmat>,
		<betterwithaddons:wood_lamp>,
		<betterwithaddons:wool:1>,
		<betterwithaddons:wool:2>,
		<betterwithaddons:wool:3>,
		<betterwithaddons:wool:4>,
		<betterwithaddons:wool:5>,
		<betterwithaddons:wool:6>,
		<betterwithaddons:wool:7>,
		<betterwithaddons:wool:8>,
		<betterwithaddons:wool:9>,
		<betterwithaddons:wool:10>,
		<betterwithaddons:wool:11>,
		<betterwithaddons:wool:12>,
		<betterwithaddons:wool:13>,
		<betterwithaddons:wool:14>,
		<betterwithaddons:wool:15>,
		<betterwithaddons:wool>
	],

	stageOne.stage: [
		<betterwithaddons:adobe:1>,
		<betterwithaddons:adobe:2>,
		<betterwithaddons:adobe:3>,
		<betterwithaddons:adobe:4>,
		<betterwithaddons:adobe:5>,
		<betterwithaddons:adobe:6>,
		<betterwithaddons:adobe:7>,
		<betterwithaddons:adobe:8>,
		<betterwithaddons:adobe:9>,
		<betterwithaddons:adobe:10>,
		<betterwithaddons:adobe:11>,
		<betterwithaddons:adobe:12>,
		<betterwithaddons:adobe:13>,
		<betterwithaddons:adobe:14>,
		<betterwithaddons:adobe:15>,
		<betterwithaddons:adobe>,
		<betterwithaddons:aqueduct:*>,
		<betterwithaddons:aqueduct:1>,
		<betterwithaddons:aqueduct:2>,
		<betterwithaddons:aqueduct:3>,
		<betterwithaddons:aqueduct:4>,
		<betterwithaddons:aqueduct:5>,
		<betterwithaddons:aqueduct:6>,
		<betterwithaddons:aqueduct:7>,
		<betterwithaddons:aqueduct:8>,
		<betterwithaddons:aqueduct:9>,
		<betterwithaddons:aqueduct:10>,
		<betterwithaddons:bag:*>,
		<betterwithaddons:bag:1>,
		<betterwithaddons:bag:2>,
		<betterwithaddons:bag:3>,
		<betterwithaddons:bag:4>,
		<betterwithaddons:bag:5>,
		<betterwithaddons:bag:8>,
		<betterwithaddons:bag:9>,
		<betterwithaddons:bag:10>,
		<betterwithaddons:bag:13>,
		<betterwithaddons:bag>,
		<betterwithaddons:bolt:1>,
		<betterwithaddons:bolt:6>,
		<betterwithaddons:bolt>,
		<betterwithaddons:box>,
		<betterwithaddons:brick_stained:1>,
		<betterwithaddons:brick_stained:2>,
		<betterwithaddons:brick_stained:3>,
		<betterwithaddons:brick_stained:4>,
		<betterwithaddons:brick_stained:5>,
		<betterwithaddons:brick_stained:6>,
		<betterwithaddons:brick_stained:7>,
		<betterwithaddons:brick_stained:8>,
		<betterwithaddons:brick_stained:9>,
		<betterwithaddons:brick_stained:10>,
		<betterwithaddons:brick_stained:11>,
		<betterwithaddons:brick_stained:12>,
		<betterwithaddons:brick_stained:13>,
		<betterwithaddons:brick_stained:14>,
		<betterwithaddons:brick_stained:15>,
		<betterwithaddons:brick_stained>,
		<betterwithaddons:bricks_stained:*>,
		<betterwithaddons:chute>,
		<betterwithaddons:crate:*>,
		<betterwithaddons:crate:1>,
		<betterwithaddons:crate:2>,
		<betterwithaddons:crate:3>,
		<betterwithaddons:crate:4>,
		<betterwithaddons:crate:5>,
		<betterwithaddons:crate:6>,
		<betterwithaddons:crate:7>,
		<betterwithaddons:crate:8>,
		<betterwithaddons:crate:9>,
		<betterwithaddons:crate:10>,
		<betterwithaddons:crate:11>,
		<betterwithaddons:crate>,
		<betterwithaddons:elytra_magma>,
		<betterwithaddons:food_beetroot_cooked>,
		<betterwithaddons:food_carrot_cooked>,
		<betterwithaddons:food_egg_cooked>,
		<betterwithaddons:food_meatballs>,
		<betterwithaddons:food_potato_cooked>,
		<betterwithaddons:fusuma>,
		<betterwithaddons:inverted_gearbox>,
		<betterwithaddons:japanmat:8>,
		<betterwithaddons:japanmat:9>,
		<betterwithaddons:japanmat:10>,
		<betterwithaddons:japanmat:11>,
		<betterwithaddons:japanmat:35>,
		<betterwithaddons:japanmat:36>,
		<betterwithaddons:laxative>,
		<betterwithaddons:leaves_luretree>,
		<betterwithaddons:log_luretree_face>,
		<betterwithaddons:log_luretree>,
		<betterwithaddons:loom>,
		<betterwithaddons:material:1>,
		<betterwithaddons:material:2>,
		<betterwithaddons:material:3>,
		<betterwithaddons:material:5>,
		<betterwithaddons:sapling_luretree>,
		<betterwithaddons:scaffold>,
		<betterwithaddons:shoji>,
		<betterwithaddons:spindle>,
		<betterwithaddons:thorn_rose>,
		<betterwithaddons:weight_stone>,
		<betterwithaddons:weight_wood>,
		<betterwithaddons:zen_ironsand>,
		<betterwithaddons:zen_redsand>,
		<betterwithaddons:zen_sand>
	],

	stageTwo.stage: [
		// Gold Stuff
		<betterwithaddons:gold_carpentersaw>,
		<betterwithaddons:gold_kukri>,
		<betterwithaddons:gold_machete>,
		<betterwithaddons:gold_masonpick>,
		<betterwithaddons:gold_matchpick>,
		<betterwithaddons:gold_spade>,

		// Misc
		<betterwithaddons:aqueduct>,
		<betterwithaddons:artifact_frame>,
		<betterwithaddons:bolt:2>,
		<betterwithaddons:bundle:1>,
		<betterwithaddons:crate:12>,
		<betterwithaddons:decomat:1>,
		<betterwithaddons:decomat:2>,
		<betterwithaddons:decomat>,
		<betterwithaddons:iron_carpentersaw>,
		<betterwithaddons:iron_kukri>,
		<betterwithaddons:iron_machete>,
		<betterwithaddons:iron_masonpick>,
		<betterwithaddons:iron_spade>,
		<betterwithaddons:lattice>,
		<betterwithaddons:monument>,
		<betterwithaddons:paper_wall>,
		<betterwithaddons:pcb_block>,
		<betterwithaddons:redstone_emitter>,
		<betterwithaddons:tweakmat:1>,
		<betterwithaddons:unbaked:1>,
		<betterwithaddons:unbaked:2>,
		<betterwithaddons:unbaked:3>,
		<betterwithaddons:unbaked>,
		<betterwithaddons:wet_soap>,
		<betterwithaddons:whitebrick:1>,
		<betterwithaddons:whitebrick:2>,
		<betterwithaddons:whitebrick:3>,
		<betterwithaddons:whitebrick>
	],

	stageThree.stage: [
		<betterwithaddons:ancestry_bottle>,
		<betterwithaddons:ancestry_infuser>,
		<betterwithaddons:ancestry_sand>,
		<betterwithaddons:bag:6>,
		<betterwithaddons:bag:7>,
		<betterwithaddons:bag:11>,
		<betterwithaddons:bag:12>,
		<betterwithaddons:bag:14>,
		<betterwithaddons:bag:15>,
		<betterwithaddons:bag:16>,
		<betterwithaddons:bamboo>,
		<betterwithaddons:banner_detector>,
		<betterwithaddons:block_matcher>,
		<betterwithaddons:boots_paper>,
		<betterwithaddons:bundle:2>,
		<betterwithaddons:chandelier>,
		<betterwithaddons:cherrybox:1>,
		<betterwithaddons:cherrybox>,
		<betterwithaddons:chest_paper>,
		<betterwithaddons:congealed:5>,
		<betterwithaddons:crop_rice>,
		<betterwithaddons:crop_tea>,
		<betterwithaddons:ecksie_sapling:1>,
		<betterwithaddons:ecksie_sapling:2>,
		<betterwithaddons:ecksie_sapling:3>,
		<betterwithaddons:ecksie_sapling:4>,
		<betterwithaddons:ecksie_sapling:5>,
		<betterwithaddons:ecksie_sapling:6>,
		<betterwithaddons:ecksie_sapling:7>,
		<betterwithaddons:ecksie_sapling:8>,
		<betterwithaddons:ecksie_sapling>,
		<betterwithaddons:greatarrow_destruction>,
		<betterwithaddons:greatarrow_lightning>,
		<betterwithaddons:greatarrow>,
		<betterwithaddons:greatbow>,
		<betterwithaddons:helmet_paper>,
		<betterwithaddons:iron_matchpick>,
		<betterwithaddons:iron_sand>,
		<betterwithaddons:japanmat:6>,
		<betterwithaddons:japanmat:7>,
		<betterwithaddons:japanmat:12>,
		<betterwithaddons:japanmat:13>,
		<betterwithaddons:japanmat:14>,
		<betterwithaddons:japanmat:15>,
		<betterwithaddons:japanmat:16>,
		<betterwithaddons:japanmat:17>,
		<betterwithaddons:japanmat:18>,
		<betterwithaddons:japanmat:19>,
		<betterwithaddons:japanmat:20>,
		<betterwithaddons:japanmat:21>,
		<betterwithaddons:japanmat:22>,
		<betterwithaddons:japanmat:23>,
		<betterwithaddons:japanmat:24>,
		<betterwithaddons:japanmat:25>,
		<betterwithaddons:japanmat:26>,
		<betterwithaddons:japanmat:27>,
		<betterwithaddons:japanmat:28>,
		<betterwithaddons:japanmat:29>,
		<betterwithaddons:japanmat:30>,
		<betterwithaddons:katana>,
		<betterwithaddons:kera>,
		<betterwithaddons:legendarium>,
		<betterwithaddons:legs_paper>,
		<betterwithaddons:material>,
		<betterwithaddons:nabe>,
		<betterwithaddons:netted_screen>,
		<betterwithaddons:pavement>,
		<betterwithaddons:shinai>,
		<betterwithaddons:slat>,
		<betterwithaddons:soulsand_pile>,
		<betterwithaddons:steel_carpentersaw>,
		<betterwithaddons:steel_kukri>,
		<betterwithaddons:steel_machete>,
		<betterwithaddons:steel_masonpick>,
		<betterwithaddons:steel_matchpick>,
		<betterwithaddons:steel_spade>,
		<betterwithaddons:tanto>,
		<betterwithaddons:tatara>,
		<betterwithaddons:tea_leaves>.withTag({type: "assam"}),
		<betterwithaddons:tea_leaves>.withTag({type: "bancha"}),
		<betterwithaddons:tea_leaves>.withTag({type: "ceylon"}),
		<betterwithaddons:tea_leaves>.withTag({type: "end"}),
		<betterwithaddons:tea_leaves>.withTag({type: "gyokuro"}),
		<betterwithaddons:tea_leaves>.withTag({type: "nether"}),
		<betterwithaddons:tea_leaves>.withTag({type: "sencha"}),
		<betterwithaddons:tea_leaves>.withTag({type: "tencha"}),
		<betterwithaddons:tea_leaves>.withTag({type: "white"}),
		<betterwithaddons:tea_powder>.withTag({type: "assam"}),
		<betterwithaddons:tea_powder>.withTag({type: "bancha"}),
		<betterwithaddons:tea_powder>.withTag({type: "ceylon"}),
		<betterwithaddons:tea_powder>.withTag({type: "end"}),
		<betterwithaddons:tea_powder>.withTag({type: "gyokuro"}),
		<betterwithaddons:tea_powder>.withTag({type: "houjicha"}),
		<betterwithaddons:tea_powder>.withTag({type: "matcha"}),
		<betterwithaddons:tea_powder>.withTag({type: "nether"}),
		<betterwithaddons:tea_powder>.withTag({type: "sencha"}),
		<betterwithaddons:tea_powder>.withTag({type: "tencha"}),
		<betterwithaddons:tea_powder>.withTag({type: "white"}),
		<betterwithaddons:tea_soaked>.withTag({type: "bancha"}),
		<betterwithaddons:tea_soaked>.withTag({type: "gyokuro"}),
		<betterwithaddons:tea_soaked>.withTag({type: "sencha"}),
		<betterwithaddons:tea_soaked>.withTag({type: "tencha"}),
		<betterwithaddons:tea_wilted>.withTag({type: "assam"}),
		<betterwithaddons:tea_wilted>.withTag({type: "ceylon"}),
		<betterwithaddons:tea_wilted>.withTag({type: "end"}),
		<betterwithaddons:tea_wilted>.withTag({type: "nether"}),
		<betterwithaddons:tea_wilted>.withTag({type: "white"}),
		<betterwithaddons:teacup>,
		<betterwithaddons:wakizashi>,
		<betterwithaddons:wrought_bars>,
		<betterwithaddons:wrought_lamp>,
		<betterwithaddons:ya>,
		<betterwithaddons:yumi>,
		<betterwithaddons:zen_soulsand>
	],

	stageFive.stage: [
		//Diamond Stuff
		<betterwithaddons:diamond_carpentersaw>,
		<betterwithaddons:diamond_kukri>,
		<betterwithaddons:diamond_machete>,
		<betterwithaddons:diamond_masonpick>,
		<betterwithaddons:diamond_matchpick>,
		<betterwithaddons:diamond_spade>,

		// Misc
		<betterwithaddons:world_scale_active>,
		<betterwithaddons:world_scale_ore:1>,
		<betterwithaddons:world_scale_ore>,
		<betterwithaddons:world_scale>,
		<betterwithaddons:worldshard>
	]
};

static hiddenItems as IIngredient[] = [
	<betterwithaddons:bag:10>,
	<betterwithaddons:bolt:3>,
	<betterwithaddons:bolt:4>,
	<betterwithaddons:bolt:5>,
	<betterwithaddons:boots_samurai>,
	<betterwithaddons:chest_samurai>,
	<betterwithaddons:crop_rush>,
	<betterwithaddons:decomat:3>,
	<betterwithaddons:extra_grass:1>,
	<betterwithaddons:extra_grass:2>,
	<betterwithaddons:extra_grass:3>,
	<betterwithaddons:extra_grass>,
	<betterwithaddons:food_clownfish_cooked>,
	<betterwithaddons:food_pufferfish_baked>,
	<betterwithaddons:helmet_samurai>,
	<betterwithaddons:ink_and_quill>,
	<betterwithaddons:japanmat:31>,
	<betterwithaddons:japanmat:32>,
	<betterwithaddons:japanmat:33>,
	<betterwithaddons:japanmat:34>,
	<betterwithaddons:leafpile_sakura>,
	<betterwithaddons:legs_samurai>,
	<betterwithaddons:log_termite>,
	<betterwithaddons:material:4>,
	<betterwithaddons:material:5>,
	<betterwithaddons:material:6>,
	<betterwithaddons:poisoned_ya>,
	<betterwithaddons:rail_rusted>,
	<betterwithaddons:rotten_food>,
	<betterwithaddons:tatami_full>,
	<betterwithaddons:wheatmat>,
	<betterwithaddons:writing_table:1>,
	<betterwithaddons:writing_table:2>,
	<betterwithaddons:writing_table:3>,
	<betterwithaddons:writing_table:4>,
	<betterwithaddons:writing_table:5>,
	<betterwithaddons:writing_table>
];

function init() {
	for stageName, items in scripts.crafttweaker.staging.itemsAndRecipes.mods.betterwithaddons.stagedItems {
		ZenStager.getStage(stageName).addIngredients(items);
	}
	for ingredient in scripts.crafttweaker.staging.itemsAndRecipes.mods.betterwithaddons.hiddenItems {
		mods.jei.JEI.removeAndHide(ingredient);
		ZenStager.getStage(stageDisabled.stage).addIngredient(ingredient, false);
	}
}
