#priority -2

import crafttweaker.item.IIngredient;

var STAGE = STAGES.five;

var modIDs as string[] = [
	"compactmachines3",
	"environmentaltech",
	"mysticalagradditions",
	"mysticalagriculture",
	"rftools",
	"rftoolscontrol",
	"scannable"
];

for id in modIDs {
	for item in loadedMods[id].items {
		mods.ItemStages.addItemStage(STAGE, item);
	}
}

var stage5Items as IIngredient[] = [
	//Oredict
	<ore:dustDiamond>,
	<ore:gearDiamond>,
	<ore:oreOsmium>,

	//ContentTweaker
	<contenttweaker:sub_block_holder_0:6>, //Osmium Ore Sample
	<materialpart:titanium:cluster>, // Titanium Cluster
	<materialpart:gold:ore_galacticraftplanets_bottom>,
	<materialpart:inferium:ore_extraplanets_kepler22b_stone>,
	<materialpart:iron:ore_galacticraftcore_bottom>,
	<materialpart:prosperity:ore_extraplanets_kepler22b_stone>,

	//Misc
	<prospectors:prospector_best>,
	<rangedpumps:pump>,

	/*
		Items by "type"
	*/
	//Emerald
	<extendedcrafting:material:129>,
	<extendedcrafting:trimmed:3>,

	//Diamond Stuff
	<chiselsandbits:bitsaw_diamond>,
	<chiselsandbits:chisel_diamond>,
	<cyclicmagic:block_anvil>,
	<cyclicmagic:charm_speed>,
	<cyclicmagic:horse_upgrade_health>,
	<cyclicmagic:spikes_diamond>,
	<extendedcrafting:material:128>,
	<ironbackpacks:backpack>.withTag({packInfo: {upgrade: [], type: "ironbackpacks:diamond", spec: "STORAGE"}}),
	<ironchest:iron_chest:2>,

	/*
		Items by mod
	*/
	//Iron Chests
	<ironchest:diamond_crystal_chest_upgrade>,
	<ironchest:diamond_obsidian_chest_upgrade>,
	<ironchest:gold_diamond_chest_upgrade>,
	<ironchest:iron_chest:5>,

	//Storage Drawers
	<storagedrawers:upgrade_storage:3>,
	<storagedrawers:upgrade_storage:4>,

	//Ender Storage
	<enderstorage:ender_pouch>,
	<enderstorage:ender_storage:1>,
	<enderstorage:ender_storage>,

	//Mystical Aggriculture/Aggggggraditions
	<mysticalagradditions:dragon_egg_crop>,
	<mysticalagradditions:nether_star_crop>,
	<mysticalagradditions:nether_star_essence>,
	<mysticalagradditions:tier6_inferium_crop>,
	<mysticalagradditions:tinkering_table>,
	<mysticalagriculture:aluminum_brass_crop>,
	<mysticalagriculture:aluminum_crop>,
	<mysticalagriculture:aquamarine_crop>,
	<mysticalagriculture:ardite_crop>,
	<mysticalagriculture:basalt_crop>,
	<mysticalagriculture:black_quartz_crop>,
	<mysticalagriculture:blaze_crop>,
	<mysticalagriculture:bronze_crop>,
	<mysticalagriculture:certus_quartz_crop>,
	<mysticalagriculture:chicken_crop>,
	<mysticalagriculture:coal_crop>,
	<mysticalagriculture:cobalt_crop>,
	<mysticalagriculture:constantan_crop>,
	<mysticalagriculture:copper_crop>,
	<mysticalagriculture:cow_crop>,
	<mysticalagriculture:creeper_crop>,
	<mysticalagriculture:desh_crop>,
	<mysticalagriculture:diamond_crop>,
	<mysticalagriculture:dirt_crop>,
	<mysticalagriculture:dye_crop>,
	<mysticalagriculture:electrum_crop>,
	<mysticalagriculture:emerald_crop>,
	<mysticalagriculture:end_crop>,
	<mysticalagriculture:ender_biotite_crop>,
	<mysticalagriculture:enderman_crop>,
	<mysticalagriculture:experience_crop>,
	<mysticalagriculture:fiery_ingot_crop>,
	<mysticalagriculture:fire_crop>,
	<mysticalagriculture:fluix_crop>,
	<mysticalagriculture:ghast_crop>,
	<mysticalagriculture:glowstone_crop>,
	<mysticalagriculture:glowstone_ingot_crop>,
	<mysticalagriculture:gold_crop>,
	<mysticalagriculture:guardian_crop>,
	<mysticalagriculture:ice_crop>,
	<mysticalagriculture:iron_crop>,
	<mysticalagriculture:ironwood_crop>,
	<mysticalagriculture:knightmetal_crop>,
	<mysticalagriculture:knightslime_crop>,
	<mysticalagriculture:lapis_lazuli_crop>,
	<mysticalagriculture:lead_crop>,
	<mysticalagriculture:limestone_crop>,
	<mysticalagriculture:manyullyn_crop>,
	<mysticalagriculture:marble_crop>,
	<mysticalagriculture:menril_crop>,
	<mysticalagriculture:meteoric_iron_crop>,
	<mysticalagriculture:nature_crop>,
	<mysticalagriculture:nether_crop>,
	<mysticalagriculture:nether_quartz_crop>,
	<mysticalagriculture:nickel_crop>,
	<mysticalagriculture:obsidian_crop>,
	<mysticalagriculture:osmium_crop>,
	<mysticalagriculture:pig_crop>,
	<mysticalagriculture:platinum_crop>,
	<mysticalagriculture:quartz_enriched_iron_crop>,
	<mysticalagriculture:rabbit_crop>,
	<mysticalagriculture:redstone_crop>,
	<mysticalagriculture:refined_obsidian_crop>,
	<mysticalagriculture:rock_crystal_crop>,
	<mysticalagriculture:sheep_crop>,
	<mysticalagriculture:silicon_crop>,
	<mysticalagriculture:silver_crop>,
	<mysticalagriculture:skeleton_crop>,
	<mysticalagriculture:sky_stone_crop>,
	<mysticalagriculture:slate_crop>,
	<mysticalagriculture:slime_crop>,
	<mysticalagriculture:spider_crop>,
	<mysticalagriculture:starmetal_crop>,
	<mysticalagriculture:steel_crop>,
	<mysticalagriculture:steeleaf_crop>,
	<mysticalagriculture:stone_crop>,
	<mysticalagriculture:tier1_inferium_crop>,
	<mysticalagriculture:tier2_inferium_crop>,
	<mysticalagriculture:tier3_inferium_crop>,
	<mysticalagriculture:tier4_inferium_crop>,
	<mysticalagriculture:tier5_inferium_crop>,
	<mysticalagriculture:tin_crop>,
	<mysticalagriculture:titanium_crop>,
	<mysticalagriculture:uranium_crop>,
	<mysticalagriculture:water_crop>,
	<mysticalagriculture:wither_skeleton_crop>,
	<mysticalagriculture:wood_crop>,
	<mysticalagriculture:zombie_crop>,

	//Cyclic
	<cyclicmagic:apple_emerald>,
	<cyclicmagic:auto_crafter>,
	<cyclicmagic:beacon_potion>,
	<cyclicmagic:block_disenchanter>,
	<cyclicmagic:block_enchanter>,
	<cyclicmagic:block_forester>,
	<cyclicmagic:book_ender>,
	<cyclicmagic:builder_pattern>,
	<cyclicmagic:charm_boat>,
	<cyclicmagic:crafting_food>,
	<cyclicmagic:cyclic_wand_build>,
	<cyclicmagic:ender_wool>,
	<cyclicmagic:harvester_block>,
	<cyclicmagic:heart_food>,
	<cyclicmagic:horse_upgrade_type>,
	<cyclicmagic:inventory_food>,
	<cyclicmagic:magic_net>,
	<cyclicmagic:password_remote>,
	<cyclicmagic:purple_boots>,
	<cyclicmagic:purple_chestplate>,
	<cyclicmagic:purple_helmet>,
	<cyclicmagic:purple_leggings>,
	<cyclicmagic:soulstone>,
	<cyclicmagic:sword_ender>,
	<cyclicmagic:sword_slowness>,
	<cyclicmagic:sword_weakness>,
	<cyclicmagic:tool_elevate>,
	<cyclicmagic:tool_swap_match>,
	<cyclicmagic:tool_warp_home>,
	<cyclicmagic:tool_warp_spawn>,
	<cyclicmagic:water_spreader>,

	//Applied Energistics
	<appliedenergistics2:cell_workbench>,
	<appliedenergistics2:charged_staff>,
	<appliedenergistics2:charger>,
	<appliedenergistics2:chest>,
	<appliedenergistics2:color_applicator>,
	<appliedenergistics2:condenser>,
	<appliedenergistics2:controller>,
	<appliedenergistics2:crafting_accelerator>,
	<appliedenergistics2:crafting_monitor>,
	<appliedenergistics2:crafting_storage_1k>,
	<appliedenergistics2:crafting_storage_4k>,
	<appliedenergistics2:crafting_storage_16k>,
	<appliedenergistics2:crafting_storage_64k>,
	<appliedenergistics2:crafting_unit>,
	<appliedenergistics2:creative_energy_cell>,
	<appliedenergistics2:creative_storage_cell>,
	<appliedenergistics2:crystal_seed:600>.withTag({progress: 600}),
	<appliedenergistics2:crystal_seed:1200>.withTag({progress: 1200}),
	<appliedenergistics2:crystal_seed>.withTag({progress: 0}),
	<appliedenergistics2:dense_energy_cell>,
	<appliedenergistics2:drive>,
	<appliedenergistics2:encoded_pattern>,
	<appliedenergistics2:energy_cell>,
	<appliedenergistics2:entropy_manipulator>,
	<appliedenergistics2:io_port>,
	<appliedenergistics2:material:6>,
	<appliedenergistics2:material:9>,
	<appliedenergistics2:material:10>,
	<appliedenergistics2:material:11>,
	<appliedenergistics2:material:12>,
	<appliedenergistics2:material:13>,
	<appliedenergistics2:material:16>,
	<appliedenergistics2:material:23>,
	<appliedenergistics2:material:25>,
	<appliedenergistics2:material:26>,
	<appliedenergistics2:material:27>,
	<appliedenergistics2:material:28>,
	<appliedenergistics2:material:29>,
	<appliedenergistics2:material:30>,
	<appliedenergistics2:material:31>,
	<appliedenergistics2:material:32>,
	<appliedenergistics2:material:33>,
	<appliedenergistics2:material:34>,
	<appliedenergistics2:material:35>,
	<appliedenergistics2:material:36>,
	<appliedenergistics2:material:37>,
	<appliedenergistics2:material:38>,
	<appliedenergistics2:material:39>,
	<appliedenergistics2:material:41>,
	<appliedenergistics2:material:42>,
	<appliedenergistics2:material:47>,
	<appliedenergistics2:material:48>,
	<appliedenergistics2:material:52>,
	<appliedenergistics2:material:53>,
	<appliedenergistics2:matter_cannon>,
	<appliedenergistics2:memory_card>,
	<appliedenergistics2:molecular_assembler>,
	<appliedenergistics2:network_tool>,
	<appliedenergistics2:portable_cell>,
	<appliedenergistics2:quantum_link>,
	<appliedenergistics2:quantum_ring>,
	<appliedenergistics2:quartz_growth_accelerator>,
	<appliedenergistics2:security_station>,
	<appliedenergistics2:sky_compass>,
	<appliedenergistics2:sky_stone_block>,
	<appliedenergistics2:sky_stone_brick>,
	<appliedenergistics2:sky_stone_brick_slab>,
	<appliedenergistics2:sky_stone_brick_stairs>,
	<appliedenergistics2:sky_stone_slab>,
	<appliedenergistics2:sky_stone_small_brick>,
	<appliedenergistics2:sky_stone_small_brick_slab>,
	<appliedenergistics2:sky_stone_small_brick_stairs>,
	<appliedenergistics2:sky_stone_stairs>,
	<appliedenergistics2:smooth_sky_stone_block>,
	<appliedenergistics2:smooth_sky_stone_slab>,
	<appliedenergistics2:smooth_sky_stone_stairs>,
	<appliedenergistics2:spatial_io_port>,
	<appliedenergistics2:spatial_pylon>,
	<appliedenergistics2:spatial_storage_cell_2_cubed>,
	<appliedenergistics2:spatial_storage_cell_16_cubed>,
	<appliedenergistics2:spatial_storage_cell_128_cubed>,
	<appliedenergistics2:storage_cell_1k>,
	<appliedenergistics2:storage_cell_4k>,
	<appliedenergistics2:storage_cell_16k>,
	<appliedenergistics2:storage_cell_64k>,
	<appliedenergistics2:tiny_tnt>,
	<appliedenergistics2:view_cell>,
	<appliedenergistics2:wireless_access_point>,
	<appliedenergistics2:wireless_terminal>,

	//Cable "accessories"/panels etc
	<appliedenergistics2:part:80>,
	<appliedenergistics2:part:100>,
	<appliedenergistics2:part:280>,
	<appliedenergistics2:part:300>,
	<appliedenergistics2:part:301>,
	<appliedenergistics2:part:320>,
	<appliedenergistics2:part:340>,
	<appliedenergistics2:part:400>,
	<appliedenergistics2:part:420>,
	<appliedenergistics2:part:440>,
	<appliedenergistics2:part:460>,
	<appliedenergistics2:part:461>,
	<appliedenergistics2:part:462>,
	<appliedenergistics2:part:463>,
	<appliedenergistics2:part:467>,
	<appliedenergistics2:part:469>,
	<appliedenergistics2:part:480>,

	//Cables
	<appliedenergistics2:part:20>,
	<appliedenergistics2:part:21>,
	<appliedenergistics2:part:22>,
	<appliedenergistics2:part:23>,
	<appliedenergistics2:part:24>,
	<appliedenergistics2:part:25>,
	<appliedenergistics2:part:26>,
	<appliedenergistics2:part:27>,
	<appliedenergistics2:part:28>,
	<appliedenergistics2:part:29>,
	<appliedenergistics2:part:30>,
	<appliedenergistics2:part:31>,
	<appliedenergistics2:part:32>,
	<appliedenergistics2:part:33>,
	<appliedenergistics2:part:34>,
	<appliedenergistics2:part:35>,
	<appliedenergistics2:part:36>,
	<appliedenergistics2:part:40>,
	<appliedenergistics2:part:41>,
	<appliedenergistics2:part:42>,
	<appliedenergistics2:part:43>,
	<appliedenergistics2:part:44>,
	<appliedenergistics2:part:45>,
	<appliedenergistics2:part:46>,
	<appliedenergistics2:part:47>,
	<appliedenergistics2:part:48>,
	<appliedenergistics2:part:49>,
	<appliedenergistics2:part:50>,
	<appliedenergistics2:part:51>,
	<appliedenergistics2:part:52>,
	<appliedenergistics2:part:53>,
	<appliedenergistics2:part:54>,
	<appliedenergistics2:part:55>,
	<appliedenergistics2:part:56>,
	<appliedenergistics2:part:60>,
	<appliedenergistics2:part:61>,
	<appliedenergistics2:part:62>,
	<appliedenergistics2:part:63>,
	<appliedenergistics2:part:64>,
	<appliedenergistics2:part:65>,
	<appliedenergistics2:part:66>,
	<appliedenergistics2:part:67>,
	<appliedenergistics2:part:68>,
	<appliedenergistics2:part:69>,
	<appliedenergistics2:part:70>,
	<appliedenergistics2:part:71>,
	<appliedenergistics2:part:72>,
	<appliedenergistics2:part:73>,
	<appliedenergistics2:part:74>,
	<appliedenergistics2:part:75>,
	<appliedenergistics2:part:76>,
	<appliedenergistics2:part:500>,
	<appliedenergistics2:part:501>,
	<appliedenergistics2:part:502>,
	<appliedenergistics2:part:503>,
	<appliedenergistics2:part:504>,
	<appliedenergistics2:part:505>,
	<appliedenergistics2:part:506>,
	<appliedenergistics2:part:507>,
	<appliedenergistics2:part:508>,
	<appliedenergistics2:part:509>,
	<appliedenergistics2:part:510>,
	<appliedenergistics2:part:511>,
	<appliedenergistics2:part:512>,
	<appliedenergistics2:part:513>,
	<appliedenergistics2:part:514>,
	<appliedenergistics2:part:515>,
	<appliedenergistics2:part:516>,

	//Geolosys
	<geolosys:cluster:9>,
	<geolosys:ore:9>,
	<geolosys:ore_sample:9>,
	<geolosys:ore_sample_vanilla:5>,
	<geolosys:ore_sample_vanilla:6>,
	<geolosys:ore_vanilla:5>,
	<geolosys:ore_vanilla:6>,

	//Refined Storage
	<refinedstorage:constructor>,
	<refinedstorage:crafter_manager>,
	<refinedstorage:crafter>,
	<refinedstorage:crafting_monitor>,
	<refinedstorage:destructor>,
	<refinedstorage:detector>,
	<refinedstorage:disk_drive>,
	<refinedstorage:disk_manipulator>,
	<refinedstorage:exporter>,
	<refinedstorage:filter>,
	<refinedstorage:fluid_interface>,
	<refinedstorage:fluid_storage:1>,
	<refinedstorage:fluid_storage:2>,
	<refinedstorage:fluid_storage:3>,
	<refinedstorage:fluid_storage:4>,
	<refinedstorage:fluid_storage>,
	<refinedstorage:fluid_storage_disk:1>,
	<refinedstorage:fluid_storage_disk:2>,
	<refinedstorage:fluid_storage_disk:3>,
	<refinedstorage:fluid_storage_disk:4>,
	<refinedstorage:fluid_storage_disk>,
	<refinedstorage:fluid_storage_part:1>,
	<refinedstorage:fluid_storage_part:2>,
	<refinedstorage:fluid_storage_part:3>,
	<refinedstorage:fluid_storage_part>,
	<refinedstorage:grid:2>,
	<refinedstorage:grid:3>,
	<refinedstorage:importer>,
	<refinedstorage:interface>,
	<refinedstorage:network_receiver>,
	<refinedstorage:network_transmitter>,
	<refinedstorage:pattern>,
	<refinedstorage:portable_grid:1>,
	<refinedstorage:portable_grid>,
	<refinedstorage:reader>,
	<refinedstorage:relay>,
	<refinedstorage:security_manager>,
	<refinedstorage:storage:1>,
	<refinedstorage:storage:2>,
	<refinedstorage:storage:3>,
	<refinedstorage:storage:4>,
	<refinedstorage:storage>,
	<refinedstorage:storage_disk:1>,
	<refinedstorage:storage_disk:2>,
	<refinedstorage:storage_disk:3>,
	<refinedstorage:storage_disk:4>,
	<refinedstorage:storage_disk>,
	<refinedstorage:storage_housing>,
	<refinedstorage:storage_monitor>,
	<refinedstorage:storage_part:1>,
	<refinedstorage:storage_part:2>,
	<refinedstorage:storage_part:3>,
	<refinedstorage:storage_part>,
	<refinedstorage:upgrade:1>,
	<refinedstorage:upgrade:2>,
	<refinedstorage:upgrade:3>,
	<refinedstorage:upgrade:4>,
	<refinedstorage:upgrade:5>,
	<refinedstorage:upgrade:6>,
	<refinedstorage:upgrade:7>,
	<refinedstorage:upgrade:8>,
	<refinedstorage:upgrade:9>,
	<refinedstorage:upgrade>,
	<refinedstorage:wireless_crafting_monitor:1>,
	<refinedstorage:wireless_crafting_monitor>,
	<refinedstorage:wireless_fluid_grid:1>,
	<refinedstorage:wireless_fluid_grid>,
	<refinedstorage:wireless_grid:1>,
	<refinedstorage:wireless_grid>,
	<refinedstorage:wireless_transmitter>,
	<refinedstorage:wrench>,
	<refinedstorage:writer>,
	<refinedstorageaddons:infinite_wireless_transmitter>,
	<refinedstorageaddons:network_bag:1>,
	<refinedstorageaddons:network_bag>,
	<refinedstorageaddons:network_picker:1>,
	<refinedstorageaddons:network_picker>,
	<refinedstorageaddons:wireless_crafting_grid:1>,
	<refinedstorageaddons:wireless_crafting_grid>,

	//Environmental Tech
	<environmentaltech:aethium:*>,
	<environmentaltech:erodium:*>,
	<environmentaltech:ionite:*>,
	<environmentaltech:kyronite:*>,
	<environmentaltech:laser_lens_colored:*>,
	<environmentaltech:litherite:*>,
	<environmentaltech:lonsdaleite:*>,
	<environmentaltech:pladium:*>,

	// Valkyrie Lib
	<valkyrielib:guide>,

	//Extended Crafting
	<extendedcrafting:compressor>,
	<extendedcrafting:crafting_core>,
	<extendedcrafting:material:11>,
	<extendedcrafting:material:12>,
	<extendedcrafting:material:13>,
	<extendedcrafting:material:17>,
	<extendedcrafting:material:18>,
	<extendedcrafting:material:19>,
	<extendedcrafting:material:24>,
	<extendedcrafting:material:25>,
	<extendedcrafting:material:32>,
	<extendedcrafting:material:33>,
	<extendedcrafting:material:140>,
	<extendedcrafting:singularity:*>,
	<extendedcrafting:singularity_custom:1>,
	<extendedcrafting:singularity_custom:2>,
	<extendedcrafting:singularity_custom:3>,
	<extendedcrafting:singularity_ultimate>,
	<extendedcrafting:singularity_custom:4>,
	<extendedcrafting:singularity_custom:5>,
	<extendedcrafting:singularity_custom:6>,
	<extendedcrafting:singularity_custom:7>,
	<extendedcrafting:singularity_custom:8>,
	<extendedcrafting:storage:2>,
	<extendedcrafting:storage:3>,
	<extendedcrafting:storage:4>,
	<extendedcrafting:table_ultimate>,
	<extendedcrafting:trimmed:2>,
	<extendedcrafting:trimmed:4>,
	<extendedcrafting:trimmed:5>,

	//Spartan Shields
	<spartanshields:shield_basic_diamond>,
	<spartanshields:shield_riot_rftools>,

	//Buildcraft
	<buildcrafttransport:pipe_daizuli_item>,
	<buildcrafttransport:pipe_diamond_fluid>,
	<buildcrafttransport:pipe_diamond_item>,
	<buildcrafttransport:pipe_diamond_wood_fluid>,
	<buildcrafttransport:pipe_diamond_wood_item:*>,
	<buildcrafttransport:pipe_emzuli_item>,

	//Xnet
	<xnet:advanced_connector:1>.withTag({display: {LocName: "tile.xnet.advanced_connector_red.name"}}),
	<xnet:advanced_connector:2>.withTag({display: {LocName: "tile.xnet.advanced_connector_yellow.name"}}),
	<xnet:advanced_connector:3>.withTag({display: {LocName: "tile.xnet.advanced_connector_green.name"}}),
	<xnet:advanced_connector>.withTag({display: {LocName: "tile.xnet.advanced_connector_blue.name"}}),
	<xnet:connector:1>,
	<xnet:connector:2>,
	<xnet:connector:3>,
	<xnet:connector:4>,
	<xnet:connector>,
	<xnet:connector_upgrade>,
	<xnet:controller>,
	<xnet:facade>,
	<xnet:netcable:1>,
	<xnet:netcable:2>,
	<xnet:netcable:3>,
	<xnet:netcable:4>,
	<xnet:netcable>,
	<xnet:redstone_proxy>,
	<xnet:redstone_proxy_upd>,
	<xnet:router>,
	<xnet:xnet_manual>,

	//Mekanism
	<materialpart:osmium:ore_minecraft_stone>,
	<materialpart:osmium:ore_sample>,

	//Translocators
	<translocators:translocator_part:1>,
	<translocators:translocator_part>,

	//Chargers
	<chargers:charger:2>,
	<chargers:wireless_charger>,

	//Reborn Storage
	<rebornstorage:multicrafter:1>,
	<rebornstorage:multicrafter:2>,
	<rebornstorage:multicrafter:3>,
	<rebornstorage:multicrafter:4>,
	<rebornstorage:multicrafter>,
	<rebornstorage:storagecell:1>,
	<rebornstorage:storagecell:2>,
	<rebornstorage:storagecell:3>,
	<rebornstorage:storagecell>,
	<rebornstorage:storagecellfluid:1>,
	<rebornstorage:storagecellfluid:2>,
	<rebornstorage:storagecellfluid:3>,
	<rebornstorage:storagecellfluid>,
	<rebornstorage:storagepart:1>,
	<rebornstorage:storagepart:2>,
	<rebornstorage:storagepart:3>,
	<rebornstorage:storagepart:4>,
	<rebornstorage:storagepart:5>,
	<rebornstorage:storagepart:6>,
	<rebornstorage:storagepart:7>,
	<rebornstorage:storagepart>,

	//Overloaded
	<overloaded:compressed_cobblestone:*>,
	<overloaded:compressed_obsidian:*>,
	<overloaded:energy_extractor>,
	<overloaded:hyper_energy_receiver>,
	<overloaded:hyper_energy_sender>,
	<overloaded:hyper_fluid_receiver>,
	<overloaded:hyper_fluid_sender>,
	<overloaded:hyper_item_receiver>,
	<overloaded:hyper_item_sender>,
	<overloaded:infinite_barrel>,
	<overloaded:infinite_capacitor>,
	<overloaded:infinite_tank>,
	<overloaded:infinite_water_source>,
	<overloaded:item_interface>,
	<overloaded:linking_card>,
	<overloaded:multi_tool>,
	<overloaded:player_interface>,

	//Quantum Storage
	<quantumstorage:crate>,
	<quantumstorage:crater>,
	<quantumstorage:quantum_bag:*>,
	<quantumstorage:quantum_barrel>,
	<quantumstorage:quantum_storage_unit>,
	<quantumstorage:quantum_tank>,
	<quantumstorage:quantumcrafter>,
	<quantumstorage:quantumstoragedisk>,
	<quantumstorage:quantumstoragediskfluid>,
	<quantumstorage:trashcan>,
	<quantumstorage:trashcanfluid>,
	<quantumstorage:upgrade:1>,
	<quantumstorage:upgrade>,

	//Iron Jetpacks
	<ironjetpacks:advanced_coil>,
	<ironjetpacks:basic_coil>,
	<ironjetpacks:diamond_capacitor>,
	<ironjetpacks:diamond_cell>,
	<ironjetpacks:diamond_jetpack>,
	<ironjetpacks:diamond_thruster>,
	<ironjetpacks:electrum_capacitor>,
	<ironjetpacks:electrum_cell>,
	<ironjetpacks:electrum_jetpack>,
	<ironjetpacks:electrum_thruster>,
	<ironjetpacks:emerald_capacitor>,
	<ironjetpacks:emerald_cell>,
	<ironjetpacks:emerald_jetpack>,
	<ironjetpacks:emerald_thruster>,
	<ironjetpacks:strap>
];

for item in stage5Items {
	mods.ItemStages.addItemStage(STAGE, item);
}

//TODO: Handle better
//Leave this to allow Dragon Scales to be used in Stage 4
mods.ItemStages.removeItemStage(<mysticalagradditions:stuff:3>);
mods.ItemStages.addItemStage(STAGES.four, <mysticalagradditions:stuff:3>);
mods.ItemStages.removeItemStage(<mysticalagradditions:stuff:1>);
mods.ItemStages.addItemStage(STAGES.three, <mysticalagradditions:stuff:1>);

//TODO: Handle better
//Set soulstone to stage 3
var soulstoneItems as IIngredient[] = [
	<mysticalagriculture:cobbled_soulstone_slab>,
	<mysticalagriculture:cobbled_soulstone_stairs>,
	<mysticalagriculture:cobbled_soulstone_wall>,
	<mysticalagriculture:soulstone:1>,
	<mysticalagriculture:soulstone:2>,
	<mysticalagriculture:soulstone:3>,
	<mysticalagriculture:soulstone:4>,
	<mysticalagriculture:soulstone:5>,
	<mysticalagriculture:soulstone:6>,
	<mysticalagriculture:soulstone>,
	<mysticalagriculture:soulstone_brick_slab>,
	<mysticalagriculture:soulstone_brick_stairs>,
	<mysticalagriculture:soulstone_brick_wall>,
	<mysticalagriculture:soulstone_slab>
];

for item in soulstoneItems {
	mods.ItemStages.removeItemStage(item);
	mods.ItemStages.addItemStage(STAGES.three, item);
}
