import crafttweaker.item.IItemStack;

/*
	Everything ProjectE
*/

var STAGE = STAGES.projecte;

var projecteItems as IItemStack[] = [
	<projecte:alchemical_chest>,
	<projecte:collector_mk1>,
	<projecte:collector_mk2>,
	<projecte:collector_mk3>,
	<projecte:condenser_mk1>,
	<projecte:condenser_mk2>,
	<projecte:dm_furnace>,
	<projecte:dm_pedestal>,
	<projecte:fuel_block:1>,
	<projecte:fuel_block:2>,
	<projecte:fuel_block>,
	<projecte:interdiction_torch>,
	<projecte:item.pe_alchemical_bag:1>,
	<projecte:item.pe_alchemical_bag:10>,
	<projecte:item.pe_alchemical_bag:11>,
	<projecte:item.pe_alchemical_bag:12>,
	<projecte:item.pe_alchemical_bag:13>,
	<projecte:item.pe_alchemical_bag:14>,
	<projecte:item.pe_alchemical_bag:15>,
	<projecte:item.pe_alchemical_bag:2>,
	<projecte:item.pe_alchemical_bag:3>,
	<projecte:item.pe_alchemical_bag:4>,
	<projecte:item.pe_alchemical_bag:5>,
	<projecte:item.pe_alchemical_bag:6>,
	<projecte:item.pe_alchemical_bag:7>,
	<projecte:item.pe_alchemical_bag:8>,
	<projecte:item.pe_alchemical_bag:9>,
	<projecte:item.pe_alchemical_bag>,
	<projecte:item.pe_arcana_ring>.withTag({Mode: 0 as byte}),
	<projecte:item.pe_arcana_ring>.withTag({Mode: 1 as byte}),
	<projecte:item.pe_arcana_ring>.withTag({Mode: 2 as byte}),
	<projecte:item.pe_arcana_ring>.withTag({Mode: 3 as byte}),
	<projecte:item.pe_archangel_smite>.withTag({}),
	<projecte:item.pe_black_hole>.withTag({}),
	<projecte:item.pe_body_stone>,
	<projecte:item.pe_catalitic_lens>.withTag({}),
	<projecte:item.pe_covalence_dust:1>,
	<projecte:item.pe_covalence_dust:2>,
	<projecte:item.pe_covalence_dust>,
	<projecte:item.pe_destruction_catalyst>.withTag({}),
	<projecte:item.pe_divining_rod_1>.withTag({}),
	<projecte:item.pe_divining_rod_2>.withTag({}),
	<projecte:item.pe_divining_rod_3>.withTag({}),
	<projecte:item.pe_dm_armor_0>,
	<projecte:item.pe_dm_armor_1>,
	<projecte:item.pe_dm_armor_2>,
	<projecte:item.pe_dm_armor_3>,
	<projecte:item.pe_dm_axe>.withTag({}),
	<projecte:item.pe_dm_hammer>.withTag({}),
	<projecte:item.pe_dm_hoe>.withTag({}),
	<projecte:item.pe_dm_pick>.withTag({}),
	<projecte:item.pe_dm_shears>.withTag({}),
	<projecte:item.pe_dm_shovel>.withTag({}),
	<projecte:item.pe_dm_sword>.withTag({}),
	<projecte:item.pe_evertide_amulet>,
	<projecte:item.pe_fuel:1>,
	<projecte:item.pe_fuel:2>,
	<projecte:item.pe_fuel>,
	<projecte:item.pe_gem_armor_0>,
	<projecte:item.pe_gem_armor_1>,
	<projecte:item.pe_gem_armor_2>,
	<projecte:item.pe_gem_armor_3>,
	<projecte:item.pe_gem_density>.withTag({}),
	<projecte:item.pe_harvest_god>,
	<projecte:item.pe_hyperkinetic_lens>.withTag({}),
	<projecte:item.pe_ignition>,
	<projecte:item.pe_klein_star:1>.withTag({}),
	<projecte:item.pe_klein_star:2>.withTag({}),
	<projecte:item.pe_klein_star:3>.withTag({}),
	<projecte:item.pe_klein_star:4>.withTag({}),
	<projecte:item.pe_klein_star:5>.withTag({}),
	<projecte:item.pe_klein_star>.withTag({}),
	<projecte:item.pe_life_stone>,
	<projecte:item.pe_matter:1>,
	<projecte:item.pe_matter>,
	<projecte:item.pe_mercurial_eye>.withTag({}),
	<projecte:item.pe_mind_stone>,
	<projecte:item.pe_philosophers_stone>.withTag({}),
	<projecte:item.pe_repair_talisman>,
	<projecte:item.pe_ring_iron_band>,
	<projecte:item.pe_rm_armor_0>,
	<projecte:item.pe_rm_armor_1>,
	<projecte:item.pe_rm_armor_2>,
	<projecte:item.pe_rm_armor_3>,
	<projecte:item.pe_rm_axe>.withTag({}),
	<projecte:item.pe_rm_hammer>.withTag({}),
	<projecte:item.pe_rm_hoe>.withTag({}),
	<projecte:item.pe_rm_katar>.withTag({}),
	<projecte:item.pe_rm_morning_star>.withTag({}),
	<projecte:item.pe_rm_pick>.withTag({}),
	<projecte:item.pe_rm_shears>.withTag({}),
	<projecte:item.pe_rm_shovel>.withTag({}),
	<projecte:item.pe_rm_sword>.withTag({}),
	<projecte:item.pe_soul_stone>,
	<projecte:item.pe_swrg>,
	<projecte:item.pe_time_watch>.withTag({}),
	<projecte:item.pe_tome>,
	<projecte:item.pe_transmutation_tablet>,
	<projecte:item.pe_void_ring>.withTag({teleportCooldown: 0 as byte}),
	<projecte:item.pe_volcanite_amulet>,
	<projecte:item.pe_zero_ring>.withTag({}),
	<projecte:matter_block:1>,
	<projecte:matter_block>,
	<projecte:nova_cataclysm>,
	<projecte:nova_catalyst>,
	<projecte:relay_mk1>,
	<projecte:relay_mk2>,
	<projecte:relay_mk3>,
	<projecte:rm_furnace>,
	<projecte:transmutation_table>
];

for item in projecteItems {
	mods.ItemStages.addItemStage(STAGE, item);
}

var projecteHiddenItems as IItemStack[] = [
	<projecte:item.pe_fire_projectile>,
	<projecte:item.pe_lava_orb>,
	<projecte:item.pe_lens_explosive>,
	<projecte:item.pe_manual>,
	<projecte:item.pe_randomizer>,
	<projecte:item.pe_water_orb>,
	<projecte:item.pe_wind_projectile>
];

for hiddenitem in projecteHiddenItems {
	mods.jei.JEI.hide(hiddenitem);
}
