
var modIDs = [
"cookingforblockheads",
"elevatorid",
"jp.crafterkina.pipes",
"modularmachinery",
"nuclearphysics",
"modularrouters",
"quantumstorage",
"storagenetwork"
] as string[];
for id in modIDs {
    for item in loadedMods[id].items {
        mods.ItemStages.addItemStage("four", item);
    }
}



mods.ItemStages.addItemStage("four", <prospectors:prospector_high>);

mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "essence", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "meat", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "latex", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "sewage", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "sludge", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "biofuel", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "if.pink_slime", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "if.protein", Amount: 1000}));


//Industrial Foregoing

mods.ItemStages.addItemStage("four", <industrialforegoing:wither_builder>);
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "essence", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "meat", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "latex", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "sewage", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "sludge", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "biofuel", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "if.pink_slime", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "if.protein", Amount: 1000}));

mods.ItemStages.addItemStage("four", <industrialforegoing:petrified_fuel_generator>);
mods.ItemStages.addItemStage("four", <industrialforegoing:enchantment_refiner>);
mods.ItemStages.addItemStage("four", <industrialforegoing:enchantment_extractor>);
mods.ItemStages.addItemStage("four", <industrialforegoing:enchantment_aplicator>);
mods.ItemStages.addItemStage("four", <industrialforegoing:mob_relocator>);
mods.ItemStages.addItemStage("four", <industrialforegoing:potion_enervator>);
mods.ItemStages.addItemStage("four", <industrialforegoing:animal_independence_selector>);
mods.ItemStages.addItemStage("four", <industrialforegoing:animal_stock_increaser>);
mods.ItemStages.addItemStage("four", <industrialforegoing:crop_sower>);
mods.ItemStages.addItemStage("four", <industrialforegoing:crop_enrich_material_injector>);
mods.ItemStages.addItemStage("four", <industrialforegoing:crop_recolector>);
mods.ItemStages.addItemStage("four", <industrialforegoing:black_hole_unit>);
mods.ItemStages.addItemStage("four", <industrialforegoing:water_condensator>);
mods.ItemStages.addItemStage("four", <industrialforegoing:water_resources_collector>);
mods.ItemStages.addItemStage("four", <industrialforegoing:animal_resource_harvester>);
mods.ItemStages.addItemStage("four", <industrialforegoing:mob_slaughter_factory>);
mods.ItemStages.addItemStage("four", <industrialforegoing:mob_duplicator>);
mods.ItemStages.addItemStage("four", <industrialforegoing:block_destroyer>);
mods.ItemStages.addItemStage("four", <industrialforegoing:block_placer>);
mods.ItemStages.addItemStage("four", <industrialforegoing:tree_fluid_extractor>);
mods.ItemStages.addItemStage("four", <industrialforegoing:latex_processing_unit>);
mods.ItemStages.addItemStage("four", <industrialforegoing:sewage_composter_solidifier>);
mods.ItemStages.addItemStage("four", <industrialforegoing:animal_byproduct_recolector>);
mods.ItemStages.addItemStage("four", <industrialforegoing:sludge_refiner>);
mods.ItemStages.addItemStage("four", <industrialforegoing:mob_detector>);
mods.ItemStages.addItemStage("four", <industrialforegoing:lava_fabricator>);
mods.ItemStages.addItemStage("four", <industrialforegoing:bioreactor>);
mods.ItemStages.addItemStage("four", <industrialforegoing:biofuel_generator>);
mods.ItemStages.addItemStage("four", <industrialforegoing:ore_processor>);
mods.ItemStages.addItemStage("four", <industrialforegoing:black_hole_controller>);
mods.ItemStages.addItemStage("four", <industrialforegoing:dye_mixer>);
mods.ItemStages.addItemStage("four", <industrialforegoing:enchantment_invoker>);
mods.ItemStages.addItemStage("four", <industrialforegoing:spores_recreator>);
mods.ItemStages.addItemStage("four", <industrialforegoing:animal_growth_increaser>);
mods.ItemStages.addItemStage("four", <industrialforegoing:material_stonework_factory>);
mods.ItemStages.addItemStage("four", <industrialforegoing:black_hole_tank>);
mods.ItemStages.addItemStage("four", <industrialforegoing:resourceful_furnace>);
mods.ItemStages.addItemStage("four", <industrialforegoing:villager_trade_exchanger>);
mods.ItemStages.addItemStage("four", <industrialforegoing:energy_field_provider>);
mods.ItemStages.addItemStage("four", <industrialforegoing:oredictionary_converter>);
mods.ItemStages.addItemStage("four", <industrialforegoing:protein_reactor>);
mods.ItemStages.addItemStage("four", <industrialforegoing:protein_generator>);
mods.ItemStages.addItemStage("four", <industrialforegoing:hydrator>);
mods.ItemStages.addItemStage("four", <industrialforegoing:item_splitter>);
mods.ItemStages.addItemStage("four", <industrialforegoing:tinydryrubber>);
mods.ItemStages.addItemStage("four", <industrialforegoing:dryrubber>);
mods.ItemStages.addItemStage("four", <industrialforegoing:plastic>);
mods.ItemStages.addItemStage("four", <industrialforegoing:fertilizer>);
mods.ItemStages.addItemStage("four", <industrialforegoing:meat_feeder>);
mods.ItemStages.addItemStage("four", <industrialforegoing:mob_imprisonment_tool>);
mods.ItemStages.addItemStage("four", <industrialforegoing:adult_filter>);
mods.ItemStages.addItemStage("four", <industrialforegoing:range_addon>);
mods.ItemStages.addItemStage("four", <industrialforegoing:range_addon:1>);
mods.ItemStages.addItemStage("four", <industrialforegoing:range_addon:2>);
mods.ItemStages.addItemStage("four", <industrialforegoing:range_addon:3>);
mods.ItemStages.addItemStage("four", <industrialforegoing:range_addon:4>);
mods.ItemStages.addItemStage("four", <industrialforegoing:range_addon:5>);
mods.ItemStages.addItemStage("four", <industrialforegoing:range_addon:6>);
mods.ItemStages.addItemStage("four", <industrialforegoing:range_addon:7>);
mods.ItemStages.addItemStage("four", <industrialforegoing:range_addon:8>);
mods.ItemStages.addItemStage("four", <industrialforegoing:range_addon:9>);
mods.ItemStages.addItemStage("four", <industrialforegoing:range_addon:10>);
mods.ItemStages.addItemStage("four", <industrialforegoing:range_addon:11>);
mods.ItemStages.addItemStage("four", <industrialforegoing:straw>);
mods.ItemStages.addItemStage("four", <industrialforegoing:pink_slime>);
mods.ItemStages.addItemStage("four", <industrialforegoing:book_manual>);
mods.ItemStages.addItemStage("four", <industrialforegoing:energy_field_addon>);
mods.ItemStages.addItemStage("four", <industrialforegoing:leaf_shearing>);


//Ore 
mods.ItemStages.addItemStage("four", <immersiveengineering:ore:5>);

//Tesla
mods.ItemStages.addItemStage("four", <teslacorelib:base_addon>);
mods.ItemStages.addItemStage("four", <teslacorelib:energy_tier1>);
mods.ItemStages.addItemStage("four", <teslacorelib:energy_tier2>);
mods.ItemStages.addItemStage("four", <teslacorelib:machine_case>);
mods.ItemStages.addItemStage("four", <teslacorelib:speed_tier1>);
mods.ItemStages.addItemStage("four", <teslacorelib:speed_tier2>);
mods.ItemStages.addItemStage("four", <teslacorelib:wrench>);
mods.ItemStages.addItemStage("four", <teslacorelib:gear_gold>);

//Actually Additions
mods.ItemStages.addItemStage("four", <actuallyadditions:magnet_ring_bauble>);
mods.ItemStages.addItemStage("four", <actuallyadditions:potion_ring_advanced_bauble:*>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_growth_ring>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_drill:*>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_bio_reactor>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_item_viewer_hopping>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_farmer>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_battery_box>);
mods.ItemStages.addItemStage("four", <actuallyadditions:battery_quintuple_bauble>);
mods.ItemStages.addItemStage("four", <actuallyadditions:battery_quadruple_bauble>);
mods.ItemStages.addItemStage("four", <actuallyadditions:battery_triple_bauble>);
mods.ItemStages.addItemStage("four", <actuallyadditions:battery_double_bauble>);
mods.ItemStages.addItemStage("four", <actuallyadditions:battery_bauble>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_quartz_stair>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_pillar_quartz_wall>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_chiseled_quartz_wall>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_quartz_wall>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_coffee_machine>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_pillar_quartz_slab>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_furnace_solar>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_greenhouse_glass>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_heat_collector>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_coal_generator>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_canola_press>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_oil_generator>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_fermenting_barrel>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_misc:4>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_misc:6>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_misc:7>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_misc:8>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_misc:9>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_feeder>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_giant_chest>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_giant_chest_medium>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_giant_chest_large>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_grinder>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_grinder_double>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_furnace_double>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_smiley_cloud>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_directional_breaker>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_misc:7>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_leaf_blower>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_filter>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_void_bag>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_bag>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_chiseled_quartz_slab>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_quartz_slab>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_pillar_quartz_stair>);
mods.ItemStages.addItemStage("four", <actuallyadditions:block_chiseled_quartz_stair>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_resonant_rice>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_coffee>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_drill_upgrade_five_by_five>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_drill_upgrade_block_placing>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_drill_upgrade_three_by_three>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_drill_upgrade_fortune_ii>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_drill_upgrade_fortune>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_drill_upgrade_silk_touch>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_drill_upgrade_speed_iii>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_drill_upgrade_speed_ii>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_drill_upgrade_speed>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_booklet>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_medium_to_large_crate_upgrade>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_small_to_medium_crate_upgrade>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_chest_to_crate_upgrade>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_crate_keeper>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_misc:16>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_misc:14>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_misc:8>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_battery>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_battery_double>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_battery_triple>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_battery_quadruple>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_battery_quintuple>);
mods.ItemStages.addItemStage("four", <actuallyadditions:item_potion_ring:*>);

//Car Mod 
mods.ItemStages.addItemStage("four", <car:tar>);
mods.ItemStages.addItemStage("four", <car:tar_slope>);
mods.ItemStages.addItemStage("four", <car:tar_slope_flat_upper>);
mods.ItemStages.addItemStage("four", <car:tar_slope_flat_lower>);
mods.ItemStages.addItemStage("four", <car:tar_slab>);
mods.ItemStages.addItemStage("four", <car:fuelstation>);
mods.ItemStages.addItemStage("four", <car:oilmill>);
mods.ItemStages.addItemStage("four", <car:blastfurnace>);
mods.ItemStages.addItemStage("four", <car:backmix_reactor>);
mods.ItemStages.addItemStage("four", <car:generator>);
mods.ItemStages.addItemStage("four", <car:split_tank>);
mods.ItemStages.addItemStage("four", <car:tank>);
mods.ItemStages.addItemStage("four", <car:crash_barrier>);
mods.ItemStages.addItemStage("four", <car:car_workshop>);
mods.ItemStages.addItemStage("four", <car:car_workshop_outter>);
mods.ItemStages.addItemStage("four", <car:cable>);
mods.ItemStages.addItemStage("four", <car:fluid_pipe>);
mods.ItemStages.addItemStage("four", <car:fluid_extractor>);
mods.ItemStages.addItemStage("four", <car:dynamo>);
mods.ItemStages.addItemStage("four", <car:crank>);
mods.ItemStages.addItemStage("four", <car:sign>);
mods.ItemStages.addItemStage("four", <car:sign_post>);
mods.ItemStages.addItemStage("four", <car:painter>);
mods.ItemStages.addItemStage("four", <car:painter_yellow>);
mods.ItemStages.addItemStage("four", <car:canola_seeds>);
mods.ItemStages.addItemStage("four", <car:canola>);
mods.ItemStages.addItemStage("four", <car:rapecake>);
mods.ItemStages.addItemStage("four", <car:iron_stick>);
mods.ItemStages.addItemStage("four", <car:engine_piston>);
mods.ItemStages.addItemStage("four", <car:engine_3_cylinder>);
mods.ItemStages.addItemStage("four", <car:engine_6_cylinder>);
mods.ItemStages.addItemStage("four", <car:car_seat>);
mods.ItemStages.addItemStage("four", <car:windshield>);
mods.ItemStages.addItemStage("four", <car:wheel>);
mods.ItemStages.addItemStage("four", <car:axle>);
mods.ItemStages.addItemStage("four", <car:container>);
mods.ItemStages.addItemStage("four", <car:car_tank>);
mods.ItemStages.addItemStage("four", <car:control_unit>);
mods.ItemStages.addItemStage("four", <car:canister>);
mods.ItemStages.addItemStage("four", <car:repair_kit>);
mods.ItemStages.addItemStage("four", <car:wrench>);
mods.ItemStages.addItemStage("four", <car:screw_driver>);
mods.ItemStages.addItemStage("four", <car:hammer>);
mods.ItemStages.addItemStage("four", <car:cable_insulator>);
mods.ItemStages.addItemStage("four", <car:key>);
mods.ItemStages.addItemStage("four", <car:car_body_part_wood>);
mods.ItemStages.addItemStage("four", <car:car_body_part_wood:1>);
mods.ItemStages.addItemStage("four", <car:car_body_part_wood:2>);
mods.ItemStages.addItemStage("four", <car:car_body_part_wood:3>);
mods.ItemStages.addItemStage("four", <car:car_body_part_wood:4>);
mods.ItemStages.addItemStage("four", <car:car_body_part_wood:5>);
mods.ItemStages.addItemStage("four", <car:arrow_front_left_right_long>);
mods.ItemStages.addItemStage("four", <car:arrow_long>);
mods.ItemStages.addItemStage("four", <car:arrow_left>);
mods.ItemStages.addItemStage("four", <car:arrow_right>);
mods.ItemStages.addItemStage("four", <car:arrow_left_right_long>);
mods.ItemStages.addItemStage("four", <car:arrow_front_left_long>);
mods.ItemStages.addItemStage("four", <car:arrow_front_right_long>);
mods.ItemStages.addItemStage("four", <car:arrow_left_dia>);
mods.ItemStages.addItemStage("four", <car:arrow_right_dia>);
mods.ItemStages.addItemStage("four", <car:arrow_front_left_right>);
mods.ItemStages.addItemStage("four", <car:arrow>);
mods.ItemStages.addItemStage("four", <car:arrow_left_short>);
mods.ItemStages.addItemStage("four", <car:arrow_right_short>);
mods.ItemStages.addItemStage("four", <car:arrow_left_right>);
mods.ItemStages.addItemStage("four", <car:arrow_front_left>);
mods.ItemStages.addItemStage("four", <car:arrow_front_right>);
mods.ItemStages.addItemStage("four", <car:arrow_left_dia_short>);
mods.ItemStages.addItemStage("four", <car:arrow_right_dia_short>);
mods.ItemStages.addItemStage("four", <car:line_middle>);
mods.ItemStages.addItemStage("four", <car:line_long>);
mods.ItemStages.addItemStage("four", <car:line_end>);
mods.ItemStages.addItemStage("four", <car:line_side_middle>);
mods.ItemStages.addItemStage("four", <car:line_side_long>);
mods.ItemStages.addItemStage("four", <car:line_side_start>);
mods.ItemStages.addItemStage("four", <car:line_side_end>);
mods.ItemStages.addItemStage("four", <car:line_side_long_left>);
mods.ItemStages.addItemStage("four", <car:line_side_long_left_front>);
mods.ItemStages.addItemStage("four", <car:line_middle_edge>);
mods.ItemStages.addItemStage("four", <car:line_corner>);
mods.ItemStages.addItemStage("four", <car:line_double>);
mods.ItemStages.addItemStage("four", <car:line_double_middle>);
mods.ItemStages.addItemStage("four", <car:line_double_end>);
mods.ItemStages.addItemStage("four", <car:arrow_zebras>);
mods.ItemStages.addItemStage("four", <car:arrow_p>);
mods.ItemStages.addItemStage("four", <car:arrow_no_parking>);
mods.ItemStages.addItemStage("four", <car:arrow_cross>);
mods.ItemStages.addItemStage("four", <car:arrow_front_left_right_long_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_long_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_left_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_right_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_left_right_long_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_front_left_long_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_front_right_long_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_left_dia_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_right_dia_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_front_left_right_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_left_short_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_right_short_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_left_right_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_front_left_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_front_right_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_left_dia_short_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_right_dia_short_yellow>);
mods.ItemStages.addItemStage("four", <car:line_middle_yellow>);
mods.ItemStages.addItemStage("four", <car:line_long_yellow>);
mods.ItemStages.addItemStage("four", <car:line_end_yellow>);
mods.ItemStages.addItemStage("four", <car:line_side_middle_yellow>);
mods.ItemStages.addItemStage("four", <car:line_side_long_yellow>);
mods.ItemStages.addItemStage("four", <car:line_side_start_yellow>);
mods.ItemStages.addItemStage("four", <car:line_side_end_yellow>);
mods.ItemStages.addItemStage("four", <car:line_side_long_left_yellow>);
mods.ItemStages.addItemStage("four", <car:line_side_long_left_front_yellow>);
mods.ItemStages.addItemStage("four", <car:line_middle_edge_yellow>);
mods.ItemStages.addItemStage("four", <car:line_corner_yellow>);
mods.ItemStages.addItemStage("four", <car:line_double_yellow>);
mods.ItemStages.addItemStage("four", <car:line_double_middle_yellow>);
mods.ItemStages.addItemStage("four", <car:line_double_end_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_zebras_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_p_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_no_parking_yellow>);
mods.ItemStages.addItemStage("four", <car:arrow_cross_yellow>);
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "canola_oil", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "methanol", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "canola_methanol_mix", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "glycerin", Amount: 1000}));
mods.ItemStages.addItemStage("four", <forge:bucketfilled>.withTag({FluidName: "bio_diesel", Amount: 1000}));

//Mob Grinding Utils
mods.ItemStages.addItemStage("four", <mob_grinding_utils:fan_upgrade>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:fan_upgrade:1>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:fan_upgrade:2>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:saw_upgrade>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:saw_upgrade:1>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:saw_upgrade:2>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:saw_upgrade:3>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:saw_upgrade:4>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:saw_upgrade:5>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:absorption_upgrade>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:spikes>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:fan>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:absorption_hopper>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:tank>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:tank_sink>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:xp_tap>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:wither_muffler>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:dragon_muffler>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:saw>);
mods.ItemStages.addItemStage("four", <mob_grinding_utils:dark_oak_stone>);

//Cyclic
mods.ItemStages.addItemStage("four", <cyclicmagic:block_shears>);
mods.ItemStages.addItemStage("four", <cyclicmagic:exp_pylon>);
mods.ItemStages.addItemStage("four", <cyclicmagic:block_user>);
mods.ItemStages.addItemStage("four", <cyclicmagic:tool_mount_inverse>);
mods.ItemStages.addItemStage("four", <cyclicmagic:block_disenchanter>);
mods.ItemStages.addItemStage("four", <cyclicmagic:charm_void>);
mods.ItemStages.addItemStage("four", <cyclicmagic:block_vacuum>);
mods.ItemStages.addItemStage("four", <cyclicmagic:ender_pearl_reuse>);
mods.ItemStages.addItemStage("four", <cyclicmagic:ender_pearl_mounted>);
mods.ItemStages.addItemStage("four", <cyclicmagic:plate_vector>);

//Factory Tech
mods.ItemStages.addItemStage("four", <factorytech:potionmixer>);
mods.ItemStages.addItemStage("four", <factorytech:htfurnace>);
mods.ItemStages.addItemStage("four", <factorytech:propfurnace>);
mods.ItemStages.addItemStage("four", <factorytech:disruptor>);
mods.ItemStages.addItemStage("four", <factorytech:stackmover>);
mods.ItemStages.addItemStage("four", <factorytech:filtermover>);
mods.ItemStages.addItemStage("four", <factorytech:bulkmover>);
mods.ItemStages.addItemStage("four", <factorytech:autopuller>);
mods.ItemStages.addItemStage("four", <factorytech:itempusher>);
mods.ItemStages.addItemStage("four", <factorytech:sequenceplacer>);
mods.ItemStages.addItemStage("four", <factorytech:watercollector>);
mods.ItemStages.addItemStage("four", <factorytech:crate>);
mods.ItemStages.addItemStage("four", <factorytech:conveyor>);
mods.ItemStages.addItemStage("four", <factorytech:elevator>);
mods.ItemStages.addItemStage("four", <factorytech:bottomhatch>);
mods.ItemStages.addItemStage("four", <factorytech:hatch>);
mods.ItemStages.addItemStage("four", <factorytech:rednotifier>);
mods.ItemStages.addItemStage("four", <factorytech:oredrill>);
mods.ItemStages.addItemStage("four", <factorytech:metalcutter>);
mods.ItemStages.addItemStage("four", <factorytech:circuitscribe>);
mods.ItemStages.addItemStage("four", <factorytech:saw>);
mods.ItemStages.addItemStage("four", <factorytech:pipe>);
mods.ItemStages.addItemStage("four", <factorytech:itemredis>);
mods.ItemStages.addItemStage("four", <factorytech:tankblock>);
mods.ItemStages.addItemStage("four", <factorytech:crucible>);
mods.ItemStages.addItemStage("four", <factorytech:compressor>);
mods.ItemStages.addItemStage("four", <factorytech:fluidpuller>);
mods.ItemStages.addItemStage("four", <factorytech:grindstone>);
mods.ItemStages.addItemStage("four", <factorytech:centrifuge>);
mods.ItemStages.addItemStage("four", <factorytech:fluiddrill>);
mods.ItemStages.addItemStage("four", <factorytech:agitator>);
mods.ItemStages.addItemStage("four", <factorytech:fridge>);
mods.ItemStages.addItemStage("four", <factorytech:sluice>);
mods.ItemStages.addItemStage("four", <factorytech:autominer>);
mods.ItemStages.addItemStage("four", <factorytech:woodcutter>);
mods.ItemStages.addItemStage("four", <factorytech:iondisperser>);
mods.ItemStages.addItemStage("four", <factorytech:teslacoil>);
mods.ItemStages.addItemStage("four", <factorytech:electroplater>);
mods.ItemStages.addItemStage("four", <factorytech:charger>);
mods.ItemStages.addItemStage("four", <factorytech:temperer>);
mods.ItemStages.addItemStage("four", <factorytech:stabilizer>);
mods.ItemStages.addItemStage("four", <factorytech:magnetizer>);
mods.ItemStages.addItemStage("four", <factorytech:energizer>);
mods.ItemStages.addItemStage("four", <factorytech:magnetblock>);
mods.ItemStages.addItemStage("four", <factorytech:spawner>);
mods.ItemStages.addItemStage("four", <factorytech:disassembler>);
mods.ItemStages.addItemStage("four", <factorytech:scaffold>);
mods.ItemStages.addItemStage("four", <factorytech:elementsword>);
mods.ItemStages.addItemStage("four", <factorytech:hardhat>);
mods.ItemStages.addItemStage("four", <factorytech:safetyvest>);
mods.ItemStages.addItemStage("four", <factorytech:workpants>);
mods.ItemStages.addItemStage("four", <factorytech:steeltoeboots>);
mods.ItemStages.addItemStage("four", <factorytech:bricks:*>);
mods.ItemStages.addItemStage("four", <factorytech:smokestack:*>);
mods.ItemStages.addItemStage("four", <factorytech:metal:*>);
mods.ItemStages.addItemStage("four", <factorytech:wrench>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:1>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:2>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:3>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:4>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:5>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:6>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:7>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:8>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:9>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:10>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:11>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:12>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:13>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:14>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:15>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:16>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:17>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:18>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:19>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:20>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:21>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:22>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:23>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:24>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:25>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:26>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:27>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:28>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:29>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:30>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:31>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:32>);
mods.ItemStages.addItemStage("four", <factorytech:machinepart:33>);
mods.ItemStages.addItemStage("four", <factorytech:salvage>);
mods.ItemStages.addItemStage("four", <factorytech:salvage:1>);
mods.ItemStages.addItemStage("four", <factorytech:salvage:2>);
mods.ItemStages.addItemStage("four", <factorytech:salvage:3>);
mods.ItemStages.addItemStage("four", <factorytech:salvage:4>);
mods.ItemStages.addItemStage("four", <factorytech:salvage:5>);
mods.ItemStages.addItemStage("four", <factorytech:salvage:6>);
mods.ItemStages.addItemStage("four", <factorytech:salvage:7>);
mods.ItemStages.addItemStage("four", <factorytech:salvage:8>);
mods.ItemStages.addItemStage("four", <factorytech:salvage:9>);
mods.ItemStages.addItemStage("four", <factorytech:salvage:10>);
mods.ItemStages.addItemStage("four", <factorytech:salvage:11>);

mods.ItemStages.addItemStage("four", <factorytech:circuit_intermediate>);
mods.ItemStages.addItemStage("four", <factorytech:circuit_intermediate:1>);
mods.ItemStages.addItemStage("four", <factorytech:circuit_intermediate:2>);
mods.ItemStages.addItemStage("four", <factorytech:circuit_intermediate:3>);
mods.ItemStages.addItemStage("four", <factorytech:circuit_intermediate:4>);
mods.ItemStages.addItemStage("four", <factorytech:circuit_intermediate:5>);
mods.ItemStages.addItemStage("four", <factorytech:circuit_intermediate:6>);
mods.ItemStages.addItemStage("four", <factorytech:circuit_intermediate:7>);
mods.ItemStages.addItemStage("four", <factorytech:circuit_intermediate:8>);
mods.ItemStages.addItemStage("four", <factorytech:circuit_intermediate:9>);
mods.ItemStages.addItemStage("four", <factorytech:circuit_intermediate:10>);
mods.ItemStages.addItemStage("four", <factorytech:circuit_intermediate:11>);
mods.ItemStages.addItemStage("four", <factorytech:circuit_intermediate:12>);
mods.ItemStages.addItemStage("four", <factorytech:tank>);
mods.ItemStages.addItemStage("four", <factorytech:tank:1>);
mods.ItemStages.addItemStage("four", <factorytech:tank:2>);
mods.ItemStages.addItemStage("four", <factorytech:tank:3>);
mods.ItemStages.addItemStage("four", <factorytech:tank:4>);
mods.ItemStages.addItemStage("four", <factorytech:intermediate>);
mods.ItemStages.addItemStage("four", <factorytech:intermediate:1>);
mods.ItemStages.addItemStage("four", <factorytech:intermediate:2>);
mods.ItemStages.addItemStage("four", <factorytech:intermediate:3>);
mods.ItemStages.addItemStage("four", <factorytech:intermediate:4>);
mods.ItemStages.addItemStage("four", <factorytech:craftstopper>);
mods.ItemStages.addItemStage("four", <factorytech:core_unfinished:99>);
mods.ItemStages.addItemStage("four", <factorytech:core_unfinished:20>);
mods.ItemStages.addItemStage("four", <factorytech:core_unfinished>);
mods.ItemStages.addItemStage("four", <factorytech:upgrade>);
mods.ItemStages.addItemStage("four", <factorytech:upgrade:1>);
mods.ItemStages.addItemStage("four", <factorytech:upgrade:2>);
mods.ItemStages.addItemStage("four", <factorytech:upgrade:3>);
mods.ItemStages.addItemStage("four", <factorytech:upgrade:4>);
mods.ItemStages.addItemStage("four", <factorytech:fluidreader>);
mods.ItemStages.addItemStage("four", <factorytech:redwatcher>);
mods.ItemStages.addItemStage("four", <factorytech:pressuregun>);
mods.ItemStages.addItemStage("four", <factorytech:handbook>);
mods.ItemStages.addItemStage("four", <factorytech:ingot:2>);
mods.ItemStages.addItemStage("four", <factorytech:ingot:3>);
mods.ItemStages.addItemStage("four", <factorytech:ore_dust:11>);
mods.ItemStages.addItemStage("four", <factorytech:ore_dust:12>);
mods.ItemStages.addItemStage("four", <factorytech:ore_dust:10>);
mods.ItemStages.addItemStage("four", <factorytech:oreblock:3>);
mods.ItemStages.addItemStage("four", <factorytech:oreblock:2>);
mods.ItemStages.addItemStage("four", <factorytech:ore_dust>);
mods.ItemStages.addItemStage("four", <factorytech:ore_dust:1>);
mods.ItemStages.addItemStage("four", <factorytech:ore_dust:2>);
mods.ItemStages.addItemStage("four", <factorytech:ore_dust:3>);

//Embers
mods.ItemStages.addItemStage("four", <embers:pipe>);
mods.ItemStages.addItemStage("four", <embers:pump>);
mods.ItemStages.addItemStage("four", <embers:item_pump>);
mods.ItemStages.addItemStage("four", <embers:item_pipe>);